"""Re-parse the 2026 poll tables from the Wikipedia PT/EN revisions current at (or before) a timestamp.

Pinning to "latest revision at or before the freeze" means no poll published after the freeze can enter.
Usage: python scripts/refresh_2026_polls.py --at 2026-10-04T01:00:00Z
Writes, from the same PT/EN revision pair:
- data/interim/polls_wiki_2026.csv and conflicts_wiki_2026.csv (first round);
- data/interim/polls_wiki_2026_runoff.csv and conflicts_wiki_2026_runoff.csv (runoff head-to-heads,
  PREREG_ADDENDUM_04 s.2);
- data/interim/polls_wiki_2026.revision.json (the oldids and revision timestamps used);
- data/SOURCES.lock.json (regenerated by `update_lock`).
"""

from __future__ import annotations

import argparse
import json

import pandas as pd

from brfc import config
from brfc.ingest import wiki_2026
from brfc.ingest.wikipedia import RAW_DIR, revision_at
from brfc.provenance import read_record, utc_now_iso

LOCK_TABLES = ("polls_wiki_*.csv", "polls_releases.csv", "polls_2014_supplement.csv")


def update_lock() -> None:
    """Regenerate data/SOURCES.lock.json from every Wikipedia revision cited by the interim poll tables.

    Scans polls_wiki_*.csv (first-round and runoff tables) and the non-Wikipedia tables polls_releases.csv and
    polls_2014_supplement.csv. Only rows that cite a Wikipedia revision (source_type `wikipedia_revision` with an
    oldid) enter the lock; release and research rows carry the SHA-256 of their source artefact instead, which
    tests/test_data_provenance.py and scripts/check_readiness.py check."""
    interim = config.DATA / "interim"
    used = set()
    for f in sorted({p for pattern in LOCK_TABLES for p in interim.glob(pattern)}):
        d = pd.read_csv(f, dtype=str)
        wiki = (d["source_type"] == "wikipedia_revision") & (d["source_revision"].fillna("").str.strip() != "")
        d = d[wiki]
        used |= set(zip(d.source_url, d.source_revision, d.source_hash, strict=True))
    recs = {}
    for p in RAW_DIR.glob("*.provenance.json"):
        r = read_record(p)
        recs[r.sha256] = r
    lock = [
        {
            "source_url": u,
            "revision": rev,
            "sha256": h,
            "retrieval_timestamp": recs[h].retrieval_timestamp if h in recs else None,
            "title": recs[h].description if h in recs else None,
            "raw_cached_locally": h in recs,
        }
        for u, rev, h in sorted(used)
    ]
    (config.DATA / "SOURCES.lock.json").write_text(
        json.dumps(lock, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--at", default=utc_now_iso(), help="UTC timestamp; latest revision at or before it is used")
    a = ap.parse_args()
    pt, pt_ts = revision_at("pt", wiki_2026.PT_TITLE, a.at)
    en, en_ts = revision_at("en", wiki_2026.EN_TITLE, a.at)
    print(f"PT oldid {pt} ({pt_ts}); EN oldid {en} ({en_ts}); at/before {a.at}")
    wiki_2026.main(pt_oldid=pt, en_oldid=en)
    update_lock()
    meta = {
        "requested_at_utc": a.at,
        "pt_oldid": pt,
        "pt_revision_timestamp": pt_ts,
        "en_oldid": en,
        "en_revision_timestamp": en_ts,
        "refreshed_utc": utc_now_iso(),
    }
    (config.DATA / "interim" / "polls_wiki_2026.revision.json").write_text(
        json.dumps(meta, indent=1) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
